/**
 * Canonical error codes (plan.md Appendix B). One flat registry — the error
 * envelope (Phase 1) and every AppError reference these, never ad-hoc strings.
 */
export const ERROR_CODES = [
  // AUTH_*
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_TOKEN_EXPIRED',
  'AUTH_TOKEN_REUSE',
  'AUTH_ACCOUNT_LOCKED',
  'AUTH_TOTP_REQUIRED',
  'AUTH_TOTP_INVALID',
  'AUTH_UNAUTHORIZED',
  'AUTH_FORBIDDEN',
  'AUTH_TOKEN_INVALID',
  'AUTH_EMAIL_ALREADY_REGISTERED',
  // TENANT_*
  'TENANT_COMPANY_CONTEXT_REQUIRED',
  'TENANT_CONTEXT_MISSING',
  'TENANT_NOT_A_MEMBER',
  'TENANT_INVITE_INVALID',
  'TENANT_ALREADY_A_MEMBER',
  'SYS_PLAN_LIMIT_EXCEEDED',
  // LEDGER_*
  'LEDGER_UNBALANCED',
  'LEDGER_IMMUTABLE',
  'LEDGER_ZERO_ENTRY',
  'LEDGER_MIN_TWO_LINES',
  'LEDGER_LINE_MUST_BE_DR_XOR_CR',
  'LEDGER_NEGATIVE_AMOUNT',
  'LEDGER_NON_INTEGER_PAISE',
  'LEDGER_PERIOD_LOCKED',
  'LEDGER_NO_TRANSACTION',
  'LEDGER_ACCOUNT_INACTIVE',
  // DOC_*
  'DOC_DUPLICATE_NUMBER',
  'DOC_ALREADY_ISSUED',
  'DOC_CANNOT_EDIT_ISSUED',
  'DOC_CANNOT_CANCEL_PAID',
  // GST_*
  'GST_INVALID_GSTIN',
  'GST_INVALID_RATE_FOR_DATE',
  'GST_HSN_DIGITS_INSUFFICIENT',
  'GST_POS_REQUIRED',
  'GST_IMS_ACTION_LOCKED',
  'GST_GSTR2B_RECOMPUTE_REQUIRED',
  // IRP_*
  'IRP_SCHEMA_INVALID',
  'IRP_REJECTED',
  'IRP_TIMEOUT',
  'IRP_WINDOW_EXPIRED',
  // AI_*
  'AI_QUOTA_EXCEEDED',
  'AI_TOOL_FORBIDDEN',
  'AI_UNKNOWN_TOOL',
  'AI_GROUNDING_FAILED',
  'AI_PROPOSAL_EXPIRED',
  // SYS_*
  'SYS_DUPLICATE_KEY',
  'SYS_RATE_LIMIT_EXCEEDED',
  'SYS_IDEMPOTENCY_KEY_REQUIRED',
  'SYS_IDEMPOTENCY_KEY_REUSE',
  'SYS_REQUEST_IN_PROGRESS',
  'SYS_CONCURRENT_MODIFICATION',
  'SYS_RETRY_TRANSACTION',
  'SYS_INTERNAL_ERROR',
  'SYS_NOT_FOUND',
  'SYS_VALIDATION_FAILED',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
