import { Router } from 'express';
import { accountRoutes } from './account.routes';
import { authRoutes } from './auth.routes';
import { journalRoutes } from './journal.routes';
import { itemRoutes, partyRoutes } from './party.routes';
import { invoiceRoutes } from './invoice.routes';
import { billRoutes, expenseRoutes } from './bill.routes';
import { paymentRoutes, webhookRoutes } from './payment.routes';
import { gstRoutes } from './gst.routes';
import { bankingRoutes } from './banking.routes';
import { reconciliationRoutes } from './reconciliation.routes';
import { jobRoutes, reportRoutes } from './report.routes';
import { billFromDocumentRoutes, documentRoutes } from './document.routes';
import { aiRoutes } from './ai.routes';
import { forecastRoutes } from './forecast.routes';
import { companyRoutes, inviteRoutes } from './company.routes';

export const v1Routes = Router();

v1Routes.use('/auth', authRoutes);
v1Routes.use('/companies', companyRoutes);
v1Routes.use('/invites', inviteRoutes);
v1Routes.use('/accounts', accountRoutes);
v1Routes.use('/journal-entries', journalRoutes);
v1Routes.use('/parties', partyRoutes);
v1Routes.use('/items', itemRoutes);
v1Routes.use('/invoices', invoiceRoutes);
v1Routes.use('/bills', billRoutes);
v1Routes.use('/expenses', expenseRoutes);
v1Routes.use('/payments', paymentRoutes);
v1Routes.use('/webhooks', webhookRoutes);
v1Routes.use('/gst', gstRoutes);
v1Routes.use('/bank-accounts', bankingRoutes);
v1Routes.use('/reconciliation', reconciliationRoutes);
v1Routes.use('/reports', reportRoutes);
v1Routes.use('/jobs', jobRoutes);
v1Routes.use('/documents', documentRoutes);
v1Routes.use('/bills', billFromDocumentRoutes);
v1Routes.use('/ai', aiRoutes);
v1Routes.use('/forecast', forecastRoutes);
